apiVersion: v1
kind: Service
metadata:
  name: connection-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: connection-service
  ports:
    - port: 8081
      targetPort: 8081